### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by kamar535** [jdittrich/figureAltCaption#1]
I would like to use this extension together with [MkDocs](http://www.mkdocs.org/). How do I install the extension?

**Comment by jdittrich** [comment]
Hii@kamar535 , I never used MkDocs with extensions. I assume it would work if you put the .py file in a folder which is in your [Python path](https://docs.python.org/2/using/cmdline.html#envvar-PYTHONPATH) and [configure MkDocs to use](http://www.mkdocs.org/user-guide/configuration/#markdown_extensions) `figureAltCaption`, probably via 

```
markdown_extensions:
    - figureAltCaption
```

Please briefly comment if this did solve your problem.

**Comment by jdittrich** [comment]
I would close this if there are no further questions.
